# Global settings applied to the whole site.  

[build]
  base    = "./wowo-app"
  publish = "./wowo-app/build"
  command = "yarn build" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200